import { Brand } from '../types';

export const BRANDS: Brand[] = [
  {
    id: 'lowrance',
    name: 'LOWRANCE',
    description: '낚시를 더 쉽게 만드는 어군탐지의 기준',
    productCount: 38,
    logo: 'LOWRANCE',
    backgroundColor: 'bg-white',
    gradientColor: 'from-red-600 to-red-800',
    hasLogo: true,
    hasOverlay: false,
  },
  {
    id: 'garmin',
    name: 'GARMIN',
    description: '바다 위 모든 항해를 하나로 연결하는 기술',
    productCount: 45,
    logo: 'GARMIN',
    backgroundColor: 'bg-black',
    gradientColor: 'from-blue-600 to-blue-800',
    hasLogo: true,
    hasOverlay: false,
  },
  {
    id: 'simrad',
    name: 'SIMRAD',
    description: '프로가 신뢰하는 프리미엄 항해 전자장비',
    productCount: 52,
    logo: 'SIMRAD',
    backgroundColor: 'oklch(0.56 0.23 27.53)',
    gradientColor: 'from-green-600 to-green-800',
    hasLogo: true,
    hasOverlay: false,
  },
  {
    id: 'camel',
    name: 'CAMEL',
    description: '현장에서 검증된 어선용 전자장비',
    productCount: 28,
    logo: 'CAMEL',
    backgroundColor: null,
    gradientColor: 'from-purple-600 to-purple-800',
    hasLogo: false,
    hasOverlay: true,
  },
  {
    id: 'standard-horizon',
    name: 'STANDARD HORIZON',
    description: '바다 위 안전을 지켜주는 해양 무전기의 표준',
    productCount: 34,
    logo: 'STANDARD HORIZON',
    backgroundColor: null,
    gradientColor: 'from-orange-600 to-orange-800',
    hasLogo: false,
    hasOverlay: true,
  },
  {
    id: 'g-zyro',
    name: 'G-ZYRO',
    description: '흔들림 없는 항해를 만드는 자이로 기술',
    productCount: 22,
    logo: 'G-ZYRO',
    backgroundColor: null,
    gradientColor: 'from-teal-600 to-teal-800',
    hasLogo: false,
    hasOverlay: true,
  },
];

