// 라우트 경로 상수
export const ROUTES = {
  HOME: '/',
  BRANDS: '/brands',
  BRAND_DETAIL: (id: string) => `/brands/${id}`,
  PRODUCT_DETAIL: (id: string) => `/product/${id}`,
  CATEGORY: (id: string) => `/category/${id}`,
  ABOUT: '/about',
  SIMULATOR: '/simulator',
  USABILITY_SERVICE: '/usability-service',
  PURCHASE_CONSULTING: '/purchase-consulting',
  // 고객지원 (구 자료실)
  SUPPORT: '/support',
  SUPPORT_NOTICE: '/support/notice',
  SUPPORT_LECTURE: '/support/lecture',
  SUPPORT_QNA: '/support/qna',
  SUPPORT_FAQ: '/support/faq',
  // 구 경로 유지 (하위 호환)
  RESOURCE_CENTER: '/support',
  RESOURCE_LECTURE: '/support/lecture',
  RESOURCE_QNA: '/support/qna',
  RESOURCE_FAQ: '/support/faq',
  RESOURCE_FISHING_POINTS: '/support/fishing-points',
  MY_PAGE: '/mypage',
  LOGIN: '/login',
  CART: '/cart',
  WISHLIST: '/wishlist',
  ORDER: '/order',
  SERVICE_REQUEST: '/service',
  CONSULTING_BOOKING: '/consulting-booking',
} as const;
